### PR TITLE
Proposal how to define protocols.

### PR DESCRIPTION
**Pull request by jtomanik**
This is my proposal, and request for comments, how we all should define our protocols at the beginning of our jog ("trucht"). What do you think, should we have one file (ie. ServiceProtocols.swift) where we define protocols and then implementation in subfolders?

### CODE REVIEW

**Comment by mateusznadolski** [comment]
I think those protocols should be extracted to the files where they belong. So `PocketItemType` protocol should be defined in the same file where the model is implemented. So if I want to extract some model or class from the project I don't have to extract file with model and protocol from some other file, but only a single file. Let me know what you think.

**Comment by mateusznadolski** [comment]
And to make it clear I'm fine with current implementation as it should speed up development process in the current state of the project.

**Comment by jtomanik** [comment]
Don't Merge!! Folder structure will change soon!

**Comment by jtomanik** [comment]
@mateusznadolski I'm fine with having protocol declarations in files with types that will implement them. Creating one file instead of many was a sign of my laziness. However if we'd like to do "proper" P(rotocol)OO (lol this acronym sounds bad ) with protocol inheritance and protocol default implementations we need to account for the case where more "abstract" protocols won't fit into any existing file and will need something separate. I'll move those declarations to the separate files but let's keep in mind the POO :)

**Comment by mateusznadolski** [comment]
👍

**Pull request closed without merging**
